version: '3.7'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
    - 8000:80
    volumes:
    - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
      - db
  web:
    build: ./entry_task
    container_name: web
    command:
      - bash
      - -c
      - |
        ./wait-for-it.sh db:3306 -- python manage.py makemigrations
        python manage.py migrate
        gunicorn entry_task.wsgi:application --workers=2 --threads=2 --worker-class=gevent --bind 0.0.0.0:8000
    volumes:
    - ./entry_task/:/entry_task
    expose:
    - 8000
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: db
    command: --default-authentication-plugin=mysql_native_password --mysqlx=0
    ports:
    - 3306:3306
    environment:
      MYSQL_DATABASE: 'entry_task_db'
      MYSQL_USER: 'athen'
      MYSQL_PASSWORD: 'P@ssword1'
      MYSQL_ROOT_PASSWORD: 'P@ssword1'