# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-11 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=b'', max_length=255)),
            ],
            options={
                'db_table': 'category_tab',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('event_id', models.IntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'comment_tab',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('location', models.CharField(default=b'65 Le Loi', max_length=255)),
                ('images', models.TextField(null=True)),
            ],
            options={
                'db_table': 'event_tab',
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_id', models.IntegerField()),
                ('category_id', models.IntegerField()),
            ],
            options={
                'db_table': 'event_category_tab',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('event_id', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'like_tab',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('event_id', models.IntegerField()),
            ],
            options={
                'db_table': 'participant_tab',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('fullname', models.CharField(max_length=255)),
                ('hashed_password', models.CharField(default=b'', max_length=255)),
                ('hash_key', models.CharField(default=b'kEy', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user_tab',
            },
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([('username',)]),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=set([('event_id', 'user_id'), ('user_id', 'event_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set([('user_id', 'event_id'), ('event_id', 'user_id')]),
        ),
        migrations.AddIndex(
            model_name='eventcategory',
            index=models.Index(fields=[b'event_id'], name=b'idx_event_id'),
        ),
        migrations.AlterUniqueTogether(
            name='eventcategory',
            unique_together=set([('category_id', 'event_id')]),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=[b'location'], name=b'idx_location'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=[b'end', b'start'], name=b'idx_end_start'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=[b'title', b'location'], name=b'idx_title_location'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=[b'event_id'], name=b'idx_event_id'),
        ),
    ]
